### ISSUE TITLE
Error in installing in Qgis 3.22

### ISSUE THREAD

**Issue by abehera91** [geowepp/QGeoWEPP#2]
ouldn't load plugin 'QGeoWEPP-demo' due to an error when calling its classFactory() method 

ImportError: DLL load failed while importing win32ui: A dynamic link library (DLL) initialization routine failed.

**Comment by shiquwucan** [comment]
![image](https://github.com/user-attachments/assets/d3e6c6c5-2c10-40a7-ac59-2bfe41b4e2a1)
Neither QGeoWEPP-demo.zip nor QGeoWEPP-main.zip can be installed successfully with QGIS 3.38 (py3.12).

**Comment by colinstiles** [comment]
I am running into same issue with `pywinauto`. Has there been any resolution to this? - January 14, 2025.

`Couldn't load plugin 'QGeoWEPP-demo' due to an error when calling its classFactory() method 

FileNotFoundError: [WinError 2] The system cannot find the file specified 
Traceback (most recent call last):
  File "C:\Users/colin.stiles/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QGeoWEPP-demo\qgeowepp.py", line 31, in 
    try: import pywinauto
         ^^^^^^^^^^^^^^^^
  File "C:\PROGRA~1/QGIS33~1.3/apps/qgis/./python\qgis\utils.py", line 923, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'pywinauto'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\PROGRA~1/QGIS33~1.3/apps/qgis/./python\qgis\utils.py", line 426, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/colin.stiles/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QGeoWEPP-demo\__init__.py", line 33, in classFactory
    from .qgeowepp import QGeoWEPP
  File "C:\PROGRA~1/QGIS33~1.3/apps/qgis/./python\qgis\utils.py", line 923, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/colin.stiles/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QGeoWEPP-demo\qgeowepp.py", line 36, in 
    subprocess.call(['pip', 'install', '-U', '--fource-reinstall', 'RequiredFiles/pywin32-228-cp39-cp39-win_amd64.whl'], creationflags= subprocess.CREATE_NO_WINDOW)
  File "C:\PROGRA~1\QGIS33~1.3\apps\Python312\Lib\subprocess.py", line 389, in call
    with Popen(*popenargs, **kwargs) as p:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PROGRA~1\QGIS33~1.3\apps\Python312\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\PROGRA~1\QGIS33~1.3\apps\Python312\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified


Python version: 3.12.3 (main, Apr 14 2024, 17:21:43) [MSC v.1938 64 bit (AMD64)] 
QGIS version: 3.36.3-Maidenhead Maidenhead, 2df96554 

Python Path:
C:/PROGRA~1/QGIS33~1.3/apps/qgis/./python
C:/Users/colin.stiles/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/colin.stiles/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS33~1.3/apps/qgis/./python/plugins
C:\PROGRA~1\QGIS33~1.3\apps\grass\grass83\etc\python
C:\Users\colin.stiles\Documents
C:\Program Files\QGIS 3.36.3\bin\python312.zip
C:\PROGRA~1\QGIS33~1.3\apps\Python312\DLLs
C:\PROGRA~1\QGIS33~1.3\apps\Python312\Lib
C:\Program Files\QGIS 3.36.3\bin
C:\PROGRA~1\QGIS33~1.3\apps\Python312
C:\PROGRA~1\QGIS33~1.3\apps\Python312\Lib\site-packages
C:\PROGRA~1\QGIS33~1.3\apps\Python312\Lib\site-packages\win32
C:\PROGRA~1\QGIS33~1.3\apps\Python312\Lib\site-packages\win32\lib
C:\PROGRA~1\QGIS33~1.3\apps\Python312\Lib\site-packages\Pythonwin
C:/Users/colin.stiles/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users/colin.stiles/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\rvt-qgis`

**Comment by jfrankenberger** [comment]
From a command window use the following command to load the missing Python module:  **`pip install pywinauto`**  After that go back to the QGis Plugins window and uncheck/check the QGeoWEPP plugin to check if was able to load.  You can also use pip directly from the QGIS path: **`"C:\Program Files\QGIS 3.34.14\apps\Python312\Scripts\pip" install pywinauto`**  (location from QGIS 3.34 LTS, will be a different path for other versions.)

**Comment by genetsewalem42-art** [comment]
What is the recommended version of qgis and python for qgeowepp plugin.
